apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  destination:
    namespace: 'apps'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'argocd/webapp'
    repoURL: 'https://github.com/kiranpe/gcp-devops-project.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
