apiVersion: v1
kind: Pod
metadata:
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  name: {{ include "nginx.name" . }}
spec:
  containers:
  - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
    name: {{ .Chart.Name }}
    resources: {}
  dnsPolicy: {{ .Values.dnsPolicy }}
  restartPolicy: {{ .Values.restartPolicy }} 
status: {}
